version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
      ruby: 2.6

    commands:
      # Install CFN-Lint, taskcat, YAMLLint
      - pip3 install cfn-lint taskcat yamllint

      # Install cfn-nag
      - gem install cfn-nag

  build:
    commands:
      # Validate Template
      - aws cloudformation validate-template --template-body file://templates/workload.template


      # Run CFN Nag
      - cfn_nag --output-format txt templates/workload.template

      # Run taskcat, strip color escape codes, output taskcat log files on STDOUT, and exit with result of taskcat
      - taskcat test run -p ci/taskcat.yml 
