version: 0.2

phases: 
    install:
        runtime-versions:
            python: 3.x
        commands:
            - echo Entered the install phase...
            - gem install cfn-nag
    pre_build:
        commands:
            - echo Entered the pre_build phase...
            - echo Current directory is $CODEBUILD_SRC_DIR
            - ls -la
            - "export dirname=${PWD##*/}"
            - echo Directory name $dirname
            - echo Installing Taskcat using pip3...
            - pip3 install cfn-lint taskcat
            - echo Verifying Taskcat installation...
            - taskcat -v
            - echo Configuring aws cli...
            - aws configure set default.region eu-west-1
    build:
        commands:
            - echo Entered the build phase...
            - echo run linting...
            - cfn-lint templates/*
            - cfn-lint templates/* > cfn_lint_output.log
            - |
              if $(grep -Fq "E" cfn_lint_output.log)
              then
                echo Linting FAILED!
                exit 1
              else
                echo Linting Passed!
                exit 0
              fi
            - echo run CFN-Nag to pinpoint security problems
            - cfn_nag_scan --input-path  templates/*
            - cfn_nag_scan --input-path  templates/* > cfn_nag_scan_output.log
            - |
              if $(grep -Fq "FAIL" cfn_nag_scan_output.log)
              then
                echo CFN-Nag security check FAILED!
                exit 1
              else
                echo CFN-Nag security check Passed!
                exit 0
              fi
            - echo run Taskcat tests...
            - taskcat test run -l
            - |
              if $(grep -Fq "CREATE_FAILED" taskcat_outputs/index.html)
              then
                echo Taskcat check FAILED!
                exit 1
              else
                echo Taskcat check Passed!
                exit 0
              fi
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
  files:
    - taskcat_outputs/*
  name: taskcat-report      
